### ISSUE TITLE
Experiments require 'dataset' package version to be <3.0

### ISSUE THREAD

**Issue by Konjak2e8** [FFY0/AdaKV#1]
When running experiment script with the command provided in README.md, an error appeared:
```bash
(adakv) (base) root@server0:/workspace/AdaKV/experiments/LongBench# bash runall.sh 
Testing /workspace/models/Mistral-7B-Instruct-v0.2 THUDM/LongBench 31500
Ada mode
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.17s/it]
Traceback (most recent call last):
  File "/workspace/AdaKV/experiments/LongBench/pred.py", line 218, in <module>
    data = load_dataset(args.dataset, f"{dataset}", split='test')#, data_dir=f"{args.dataset}/data")
  File "/root/miniconda3/envs/adakv/lib/python3.10/site-packages/datasets/load.py", line 2075, in load_dataset
    builder_instance = load_dataset_builder(
  File "/root/miniconda3/envs/adakv/lib/python3.10/site-packages/datasets/load.py", line 1833, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
TypeError: 'NoneType' object is not callable
```
By downgrading 'dataset' package version from 3.0.0 to 2.15.0, the problem was solved.

**Comment by FFY0** [comment]
It appears to be an issue with the package version. In my environment, the version of datasets is 2.19.1, for your reference.
